services:
  bot:
    build: .
    
    environment:
      - POSTGRES_HOST=psql_db

    env_file:
      - ./.env

    container_name: bot
    
    networks:
      - custom

    ports:
      - '8000:8000'


    depends_on:
      - psql_db

    command: sh -c 'python main.py'
  
  psql_db:
    image: postgres:14
    
    env_file:
      - ./.env

    networks:
      - custom

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  custom:
    name: ngrok
    external: true