services:
  ngrok:
    image: ngrok/ngrok:latest
    # restart: unless-stopped
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
  
  bot:
    build: .
    environment:
      - POSTGRES_HOST=psql_db
    env_file:
      - ./.env
    container_name: bot
    ports:
      - '8000:8000'
    depends_on:
      - psql_db
      - ngrok
    command: sh -c 'python main.py'
  
  psql_db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
