services:
  bot:
    build: .
    
    environment:
      - POSTGRES_HOST=psql_db
    
    env_file:
      - ./.env

    depends_on:
      - psql_db

    command: sh -c 'python main.py'
  
  psql_db:
    image: postgres:14
    
    env_file:
      - ./.env
    
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: